-- Record the legacy KV compatibility table in forward migration history.
--
-- Existing projects received this table from the autogenerated KV integration
-- before relational migrations were introduced. Fresh migration replay is
-- guarded in 20260520000009 because it reaches that historical seed before
-- this forward repair.

CREATE TABLE IF NOT EXISTS public.kv_store_17cae920 (
  key TEXT PRIMARY KEY,
  value JSONB NOT NULL
);

COMMENT ON TABLE public.kv_store_17cae920 IS
  'Legacy compatibility and operational key/value storage.';
